apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  storageClassName: mylocalstorage
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-sorage
spec:
  storageClassName: mylocalstorage
  capacity:
    storage: 8Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "mnt/some/new/director/structure"
    type: DirectoryOrCreate








